P12/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',views.base,name="Base"),
    path('',views.home,name="Home"),
    path('myapp/',include("myapp.urls")),
]

myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"

urlpatterns = [
    path('trial/',views.trial,name="Trial"),
    path('profile/',views.profile,name="Profile"),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def trial(request):
    return HttpResponse("<h1> Project is on AIR </h1>")

def base(request):
    return render(request,"base.html")

def home(request):
    return render(request,"myapp/home.html")

def profile(request):
    name="Pyspiders"
    return render(request,"myapp/profile.html",{'name':name})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
      <title>Base Page</title>
    {% endblock  %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>


</head>
<body>
    {% include "partials/topbar.html" %}
    {% include "partials/navbar.html" %}

    {% block content %}
      <div class="container">
          <div class="jumbotron">
              <center><h1>Welcome to Base Html Page</h1></center>
              <img src="{% static 'images/django_logo.png' %}" alt="No img found" height="200" width="200">
          </div>
      </div>
    {% endblock  %}

    {% include "partials/footer.html" %}
</body>
</html>

templates/myapp/home.html
{% extends "base.html" %}

{% block title %}
  <title>Home Page</title>
{% endblock  %}

{% block content %}
  <div class="container">
      <div class="jumbotron">
          <center><h1>Welcome to Home Page</h1></center>
      </div>
  </div>
{% endblock  %}

templates/myapp/profile.html
{% extends "base.html" %}

{% block title %}
  <title>Profile Page</title>
{% endblock  %}

{% block content %}
  <div class="container">
      <div class="jumbotron">
          <h1>Welcome to {{name}} profile page</h1>
      </div>
  </div>
{% endblock  %}

templates/partials/footer.html
<!--Footer html page-->
<div class="alert alert-info" role="alert">
    <center><h3>Footer</h3></center>
</div>

templates/partials/navbar.html
<!--Nav Bar html page-->
<div class="container">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'Home' %}">Home</a>
        </li>
        <li>
            <a class="nav-link" href="{% url 'myapp:Profile' %}">Profile</a>
        </li>
    </ul>
</div>

templates/partials/topbar.html
<!--Top Bar html page-->
<div class="alert alert-secondary" role="alert">
    <center><h3>Top Bar</h3></center>
</div>